services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start.sh
    volumes:
      - .:/workspace/dbd_randomizer_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_ENV=development

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
