services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./start.sh
    volumes:
      - .:/workspace/dbd_randomizer_service
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development