# Generated by Django 4.2.7 on 2023-11-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('image_path', models.TextField()),
            ],
        ),
    ]
