# Generated by Django 4.2.7 on 2023-11-11 10:39

from django.db import migrations
from django.core.management import call_command

def load_inital_perk_data(apps, schema_editor):
    call_command('loaddata', 'perks/survivor_perk_data.json', verbosity=2)


def unload_initial_perk_data(apps, schema_editor):
    perk = apps.get_model('perk', 'Perk')
    perk.objects.filter(pk__range=(1, 66)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('perk', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_inital_perk_data, unload_initial_perk_data)
    ]
