# Generated by Django 4.1.13 on 2023-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perk', '0003_add_general_perk_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='type',
            field=models.CharField(choices=[('Survivor', 'Killer')], max_length=10),
        ),
    ]
