SECRET_KEY = "dev has all the secrets"
DEBUG = True
ALLOWED_HOSTS = ['localhost']
DATABASE_NAME = "dbd_randomizer_db_dev"
DATABASE_USER = "dev_user"
DATABASE_PASSWORD = "dev_password"
DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_DOMAIN = 'localhost'
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'https://localhost:3000']
CSRF_ALLOWED_ORIGINS = ['http://localhost:3000', 'https://localhost:3000']
CORS_ALLOWED_ORIGINS = ['http://localhost:3000', 'https://localhost:3000']
CORS_ORIGINS_WHITELIST = ['http://localhost:3000', 'https://localhost:3000']