# Generated by Django 4.2.7 on 2023-11-11 10:39

from django.db import migrations
from django.core.management import call_command

def load_inital_survivor_data(apps, schema_editor):
    call_command('loaddata', 'survivors/survivor_data.json', verbosity=2)


def unload_initial_survior_data(apps, schema_editor):
    survivor = apps.get_model('survivor', 'Survivor')
    survivor.objects.filter(pk__range=(1, 66)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_inital_survivor_data, unload_initial_survior_data)
    ]
