# Generated by Django 4.1.13 on 2023-11-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='RegisteredUser',
        ),
    ]
